# 导纳控制器配置文件
admittance_controller:
  type: "robot_hw_test/AdmittanceController"
  
  # 关节配置
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  
  # 机器人模型配置
  base_link: "base_link"
  end_effector_link: "tool0"
  
  # 导纳控制参数
  admittance:
    # 质量矩阵对角线元素 [x, y, z, rx, ry, rz]
    mass_diagonal: [1.0, 1.0, 1.0, 0.1, 0.1, 0.1]
    
    # 阻尼矩阵对角线元素 [x, y, z, rx, ry, rz]
    damping_diagonal: [10.0, 10.0, 10.0, 1.0, 1.0, 1.0]
    
    # 刚度矩阵对角线元素 [x, y, z, rx, ry, rz]
    stiffness_diagonal: [100.0, 100.0, 100.0, 10.0, 10.0, 10.0]
    
    # 力限制 (N)
    max_force: 50.0
    
    # 力矩限制 (Nm)
    max_torque: 10.0
    
    # 位置误差限制 (m)
    max_position_error: 0.1
    
    # 最大速度 (m/s)
    max_velocity: 0.5
    
    # 力滤波截止频率 (Hz)
    force_filter_cutoff: 10.0
    
    # 速度滤波截止频率 (Hz)
    velocity_filter_cutoff: 5.0

# 其他控制器配置
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# 关节轨迹控制器（可选）
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  
  # 关节限制
  joint_limits:
    joint1:
      has_velocity_limits: true
      max_velocity: 3.15
      has_acceleration_limits: true
      max_acceleration: 10.0
    joint2:
      has_velocity_limits: true
      max_velocity: 3.15
      has_acceleration_limits: true
      max_acceleration: 10.0
    joint3:
      has_velocity_limits: true
      max_velocity: 3.15
      has_acceleration_limits: true
      max_acceleration: 10.0
    joint4:
      has_velocity_limits: true
      max_velocity: 3.2
      has_acceleration_limits: true
      max_acceleration: 10.0
    joint5:
      has_velocity_limits: true
      max_velocity: 3.2
      has_acceleration_limits: true
      max_acceleration: 10.0
    joint6:
      has_velocity_limits: true
      max_velocity: 3.2
      has_acceleration_limits: true
      max_acceleration: 10.0
